CREATE TABLE FormulaMaster 
(
	FormulaID INT IDENTITY(1,1) NOT NULL,
	SiteProductMapID INT NOT NULL,
	FormulaChangeNote TEXT,
	TextureAppearanceNote TEXT,
	ProjectInfoNote TEXT,
	PackagingInfoForPowderNote TEXT,
	DatasheetNote TEXT,
	FormulaNote TEXT,
	FormulaCode VARCHAR(50),
	FormulaDescription VARCHAR(500),
	FormulaTag VARCHAR(50),
	CoreWeight NUMERIC(18, 4),
	CoatingWeight NUMERIC(18, 4),
	ToppingWeight NUMERIC(18, 4),
	FormulaStatusCode VARCHAR(100),
	FormulaReference VARCHAR(50),
	SubGroupCoreWeight NUMERIC(18, 4),
	SubGroupCoatingWeight NUMERIC(18, 4),
	SubGroupToppingweight NUMERIC(18, 4),
	FormulaTypeID INT,
	AltCode VARCHAR(50),
	RegulatoryCategoryID INT,
	ProductDescription VARCHAR(MAX),
	FlavourDescription VARCHAR(MAX),
	Qualifier VARCHAR(200),
	FormulaProjectID INT,
	FormulaCustomerID INT,
	CustomerCode VARCHAR(50),
	NutrientFormatID INT,
	AllergenCode VARCHAR(100),
	ServingUnit INT,
	CoatedRework NUMERIC(18, 2),
	TrimRework NUMERIC(18, 2),
	OpsNote TEXT,
	Preconditioning VARCHAR(500),
	PrimaryLine INT,
	DryIceUsage INT,
	SyrupBinderHeated BIT,
	SyrupBinderShear BIT,
	CookTemperature NUMERIC(18, 2),
	TankTemperature NUMERIC(18, 2),
	PipeTemperature NUMERIC(18, 2),
	MixerTemperature NUMERIC(18, 2),
	MaximumHoldingTime NUMERIC(18, 2),
	BrixRange VARCHAR(100),
	SyrupAw VARCHAR(50),
	SyrupPh VARCHAR(50),
	TransferTemperature NUMERIC(18, 2),
	UsageTemperature NUMERIC(18, 2),
	FinalDoughTemperature VARCHAR(50),
	DoughWaterActivity NUMERIC(18, 2),
	DoughDensity NUMERIC(18, 2),
	ReleaseAgent VARCHAR(100),
	PKOPercentage VARCHAR(100),
	ActualWaterPercentage NUMERIC(18, 4),
	WaterLoss NUMERIC(18, 4),
	IsRework BIT,
	SlitterWidth NUMERIC(18, 2),
	USMav NUMERIC(18, 2),
	USMavRange VARCHAR(20),
	CanadaMav NUMERIC(18, 2),
	CanadaMavRange VARCHAR(20),
	DimensionsCoreLength NUMERIC(18, 4),
	DimensionsCoreWidth NUMERIC(18, 4),
	DimensionsCoreHeight NUMERIC(18, 4),
	DimensionsCore NUMERIC(18, 4),
	DimensionsLayer NUMERIC(18, 4),
	DimensionsTopping NUMERIC(18, 4),
	DimensionsOverrideLength NUMERIC(18, 4),
	DimensionsOverrideWidth NUMERIC(18, 4),
	DimensionsOverrideHeight NUMERIC(18, 4),
	DimensionsOverrideCore NUMERIC(18, 4),
	DimensionsOverrideLayer NUMERIC(18, 4),
	DimensionsOverrideTopping NUMERIC(18, 4),
	DimensionsFinishLength NUMERIC(18, 4),
	DimensionsFinishWidth NUMERIC(18, 4),
	DimensionsFinishHeight NUMERIC(18, 4),
	DimensionsLengthLimit NUMERIC(18, 2),
	DimensionsWidthLimit NUMERIC(18, 2),
	DimensionsHeightLimit NUMERIC(18, 2),
	CircleDiameter NUMERIC(18, 2),
	CircleLineFactor NUMERIC(18, 2),
	CircleCore NUMERIC(18, 4),
	CircleLayer NUMERIC(18, 4),
	CircleTopping NUMERIC(18, 4),
	CircleLowerLimit NUMERIC(18, 2),
	CircleUpperLimit NUMERIC(18, 2),
	QcSpecificationNote TEXT,
	BarformatEquipment VARCHAR(100),
	BarFormatForm VARCHAR(100),
	BarFormatCore VARCHAR(100),
	BarFormatTop VARCHAR(100),
	BarFormatDescription VARCHAR(100),
	BarFormatTopping VARCHAR(100),
	BarFormatLocation VARCHAR(100),
	BarFormatCoating VARCHAR(100),
	BarFormatDrizzle VARCHAR(100),
	BarFormatWoody VARCHAR(100),
	PowderReconstitution  VARCHAR(200),
	PowderLiquidAmountID INT,
	PowderBatchSize DECIMAL(18, 4),
	PowderBlenderID INT,
	PowderBulkDensity DECIMAL(18, 4),
	PowderFillWidth INT,
	PowderUnitID INT,
	DieNumber VARCHAR(50),
	KcalPer100g DECIMAL(30,15),
	PricePer100g DECIMAL(30,15),
	TotalFatInPercent DECIMAL(30,15),
	TotalCarbInPercent DECIMAL(30,15),
	TotalFiberInPercent DECIMAL(30,15),
	TotalSugerInPercent DECIMAL(30,15),
	TotalProteinInPercent DECIMAL(30,15),
	PrimaryProductionLineID INT,
	IsAllClaimVerify BIT NOT NULL CONSTRAINT DF_FormulaMaster_IsAllClaimVerify DEFAULT(0),
	IsActive BIT NOT NULL CONSTRAINT DF_FormulaMaster_IsActive DEFAULT(1),
	IsDeleted BIT NOT NULL CONSTRAINT DF_FormulaMaster_IsDeleted DEFAULT(0),
	CreatedBy INT,
	CreatedOn DATETIME NOT NULL CONSTRAINT DF_FormulaMaster_CreatedOn DEFAULT(GETDATE()),
	UpdatedBy INT,
	UpdatedOn DATETIME,
	CONSTRAINT PK_FormulaMaster PRIMARY KEY (FormulaID),
	CONSTRAINT FK_FormulaMaster_SiteProductTypeMapping FOREIGN KEY (SiteProductMapID) REFERENCES SiteProductTypeMapping(SiteProductMapID),
	CONSTRAINT FK_FormulaMaster_SiteProductionLineMapping FOREIGN KEY (PrimaryProductionLineID) REFERENCES SiteProductionLineMapping(SiteProductionLineMapID)
)