CREATE TABLE HACCPMaster
(
	HACCPID INT IDENTITY(1,1) NOT NULL,
	HACCPType VARCHAR(20) NOT NULL,
	HACCPDescription VARCHAR(200),
	IsActive BIT NOT NULL CONSTRAINT DF_HACCPMaster_IsActive DEFAULT(1),
	IsDeleted BIT NOT NULL CONSTRAINT DF_HACCPMaster_IsDeleted DEFAULT(0),
	CreatedBy INT,
	CreatedOn DATETIME NOT NULL CONSTRAINT DF_HACCPMaster_CreatedOn DEFAULT(GETDATE()),
	UpdatedBy INT,
	UpdatedOn DATETIME,
	CONSTRAINT PK_HACCPMaster PRIMARY KEY (HACCPID)
)