CREATE TABLE IngredientMaster
(
	IngredientID INT IDENTITY(1,1) NOT NULL,
	IRWPart VARCHAR(50),
	ANJResearchCode VARCHAR(50),
	ONTResearchCode VARCHAR(50),
	S30SubAssemblyCode VARCHAR(50),
	JDECode VARCHAR(50),
	IngredientUsed VARCHAR(30),
	RMDescription VARCHAR(30),
	OriginCountry VARCHAR(200),
	Viscosity VARCHAR(50),
	Microns VARCHAR(50),
	HACCPRisk INT,
	IngredientBreakDown VARCHAR(MAX),
	IngredientList VARCHAR(MAX),
	InternalXReference VARCHAR(100),
	ExternalXReference VARCHAR(100),
	Sulfites DECIMAL(30, 15),
	OptimumStorageCondition VARCHAR(50),
	GeneralNote TEXT,
	AltCode VARCHAR(50),
	IngredientCategoryID INT,
	NutrientLink VARCHAR(50),
	NutrientDescription VARCHAR(MAX),
	DataSourceNote TEXT,
	StorageCode VARCHAR(50),
	PreConditionCode VARCHAR(50),
	StorageInformation TEXT,
	IPPBagSize VARCHAR(50),
	AlertReview VARCHAR(50),
	IsDataReviewedNutrient BIT,
	IsDataReviewedAllergen BIT,
	AlertReviewDate DATETIME,
	UsageAlert VARCHAR(150),
	ExclusivityAlert VARCHAR(200),
	AlertCustomerAbbr VARCHAR(50),
	SupplierSeeNotes VARCHAR(50),
	Vegetarian VARCHAR(10),
	Vegan VARCHAR(10),
	[PorkPresent] VARCHAR(10),
	IsRBST BIT,
	IsPreservatives BIT,
	IsRSPO BIT,
	RSPODate DATETIME,
	RSPOCertificateNumber VARCHAR(50),
	IsSynthitic BIT,
	IsWADA BIT,
	[WADAYear] INT,
	GeneralDate DATETIME,
	RegulatoryStatusID INT,
	SterilizationMethodID INT,
	GlutenStatusID INT,
	OrganicStatusID INT,
	GMOStatus VARCHAR(100),
	OrganicIssueDate DATETIME,
	OrganicExpireDate DATETIME,
	HalalStatusID INT,
	IsHalalStatement BIT,
	AllergenNote TEXT,
	HighRiskCrossContSpecies TEXT,
	PrimaryUnitWeight DECIMAL(10,5),
	UnitOfMeasurementID INT,
	CFRReferenceNo VARCHAR(50),
	GRASNo VARCHAR(50),
	HTSNo VARCHAR(50),
	ShakleeCode VARCHAR(50),
	CASNumber VARCHAR(50),
	NAFTAExpireDate DATETIME,
	SupplierNote TEXT,
	ShelfLife INT,
	Biological VARCHAR(100),
	Chemical VARCHAR(100),
	Physical VARCHAR(100),
	ControlMechanismBiological VARCHAR(100),
	ControlMechanismPhysical VARCHAR(300),
	ControlMachanismChemical VARCHAR(300),
	Micro VARCHAR(100),
	ForeignMatter VARCHAR(100),
	FSApproval DATETIME,
	TGApproval VARCHAR(100),
	PackageOption VARCHAR(100),
	SupplierPackage VARCHAR(100),
	ProcurementDetail VARCHAR(100),
	HandSort VARCHAR(50),
	Cadmium DECIMAL(30, 15),
	[Lead] DECIMAL(30, 15),
	Arsenic DECIMAL(30, 15),
	Mercury DECIMAL(30, 15),
	NutrientDataChangeDate DATETIME,
	UsageBarLimit VARCHAR(100),
	UsagePowderLimit VARCHAR(100),
	UsageCanadaLimit VARCHAR(100),
	GeneralDataChangedBy INT,
	ClaimAmountUnit VARCHAR(10),
	ActiveNutrient VARCHAR(50),
	NutrientActivity VARCHAR(50),
	UsageRangeLimit VARCHAR(100),
	Pro65Chemical VARCHAR(1000),
	GeneralRMDescription VARCHAR(100),
	SortingPart VARCHAR(50),
	IsAllergenPendingDocument BIT NOT NULL CONSTRAINT DF_IngredientMaster_IsAllergenPendingDocument DEFAULT(0),
	NeedInputForSulfites BIT,
	IsActive BIT NOT NULL CONSTRAINT DF_IngredientMaster_IsActive DEFAULT(1),
	IsDeleted BIT NOT NULL CONSTRAINT DF_IngredientMaster_IsDeleted DEFAULT(0),
	CreatedBy INT,
	CreatedOn DATETIME NOT NULL CONSTRAINT DF_IngredientMaster_CreatedOn DEFAULT(GETDATE()),
	UpdatedBy INT,
	UpdatedOn DATETIME
	CONSTRAINT PK_IngredientMaster PRIMARY KEY (IngredientID),
	CONSTRAINT FK_IngredientMaster_IngredientCategoryMaster FOREIGN KEY (IngredientCategoryID) REFERENCES IngredientCategoryMaster(IngredientCategoryID),
	CONSTRAINT FK_IngredientMaster_RMStatusMaster_Regulatory FOREIGN KEY (RegulatoryStatusID) REFERENCES RMStatusMaster(RMStatusMasterID),
	CONSTRAINT FK_IngredientMaster_RMStatusMaster_Gluten FOREIGN KEY (GlutenStatusID) REFERENCES RMStatusMaster(RMStatusMasterID),
	CONSTRAINT FK_IngredientMaster_RMStatusMaster_Halal FOREIGN KEY (HalalStatusID) REFERENCES RMStatusMaster(RMStatusMasterID),
	CONSTRAINT FK_IngredientMaster_RMStatusMaster_Organic FOREIGN KEY (OrganicStatusID) REFERENCES RMStatusMaster(RMStatusMasterID),
	CONSTRAINT FK_IngredientMaster_RMStatusMaster_Sterilization FOREIGN KEY (SterilizationMethodID) REFERENCES RMStatusMaster(RMStatusMasterID),
	CONSTRAINT FK_IngredientMaster_UnitOfMeasurementMaster FOREIGN KEY (UnitOfMeasurementID) REFERENCES UnitOfMeasurementMaster(UnitOfMeasurementID)
)