CREATE TABLE RMStatusMaster
(
	RMStatusMasterID INT IDENTITY(1,1) NOT NULL,
	RMStatusType VARCHAR(20) NOT NULL,
	RMStatus VARCHAR(200) NOT NULL,
	IsActive BIT NOT NULL CONSTRAINT DF_RMStatusMaster_IsActive DEFAULT(1),
	IsDeleted BIT NOT NULL CONSTRAINT DF_RMStatusMaster_IsDeleted DEFAULT(0),
	CreatedBy INT,
	CreatedOn DATETIME NOT NULL CONSTRAINT DF_RMStatusMaster_CreatedOn DEFAULT(GETDATE()),
	UpdatedBy INT,
	UpdatedOn DATETIME,
	CONSTRAINT PK_RMStatusMaster PRIMARY KEY (RMStatusMasterID)
)