using FM21.Core;
using FM21.Core.Model;
using FM21.Entities;
using System.Collections.Generic;
using System.Data;
using System.Threading.Tasks;

namespace FM21.Service
{
    public interface IIngredientMasterService
    {
        Task<GeneralResponse<string>> GetAutoGeneratedJDECode(int ingredientCategoryCode);
        Task<GeneralResponse<string>> GetAutoGeneratedS30Code(int siteID, int ingredientCategoryCode);
        Task<GeneralResponse<Dictionary<string, string>>> GetAutoGeneratedRAndDCode();
        Task<GeneralResponse<int>> CheckCodeIsExist(string code);
        Task<GeneralResponse<bool>> SaveNewIngredient(IngredientModel ingredientModel);
        Task<GeneralResponse<bool>> UpdateIngredient(IngredientModel ingredientModel);
        Task<GeneralResponse<IngredientModel>> GetIngredientByIngredientID(int ingredientID);
        Task<GeneralResponse<DataTable>> GetSupplierByIngredientID(int ingredientID);
        Task<GeneralResponse<DataTable>> GetNutrientByIngredientID(int ingredientID);
        Task<GeneralResponse<ICollection<IngredientCategoryMaster>>> GetAllIngredientCategory();
        Task<GeneralResponse<ICollection<AlertMaster>>> GetAlertMasterData(string alertType);
        Task<PagedTableResponse<DataTable>> SearchIngredient(IngredientSearchFilter searchFilter);
        Task<GeneralResponse<bool>> DeleteIngredient(int id);
        Task<GeneralResponse<bool>> UpdateIngredientSearchHistory(int userID, string searchData);
        Task<GeneralResponse<ICollection<IngredientSearchHistory>>> GetIngredientSearchHistory(int userID);
        Task<GeneralResponse<DataTable>> GetIngredientReportData(string reportType, string siteIDs, string productTypeID);
        Task<GeneralResponse<DataTable>> GetIngredientCustomReportData(IngredientReportFilter searchReportFilter);
        Task<GeneralResponse<FormulaIngredientAttributes>> GetIngredientForFormula(IngredientReportFilter searchReportFilter);
        Task<GeneralResponse<DataTable>> GetIngredientPartInfo(int ingredientID); 
    }
}